import type { Theme } from "../types/template";

export const KOMITY_BLUE: Theme = {
  name: "KOMITY Blue",
  colors: {
    primary: "#2563EB",
    primaryLight: "#EFF6FF",
    accent: "#3B82F6",
    accentLight: "#DBEAFE",
    success: "#16A34A",
    successLight: "#F0FDF4",
    warning: "#D97706",
    warningLight: "#FFFBEB",
    danger: "#DC2626",
    dangerLight: "#FEF2F2",
    text: "#111827",
    textLight: "#6B7280",
    textMuted: "#9CA3AF",
    background: "#FFFFFF",
    backgroundAlt: "#F8FAFC",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
  },
  typography: {
    fontFamily: "Inter, system-ui, sans-serif",
    headingFontFamily: "Inter, system-ui, sans-serif",
    baseFontSize: 14,
    lineHeight: 1.65,
    headingSizes: { h1: 28, h2: 20, h3: 16 },
    fontWeights: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
  },
  spacing: {
    unit: 4,
    pagePadding: "28px 36px 32px",
    sectionGap: 4,
    componentGap: 3,
  },
  borders: { radius: 8, radiusLg: 12, width: 1 },
};

export const MINIMAL_LIGHT: Theme = {
  name: "Minimal Light",
  colors: {
    primary: "#1a1a1a",
    primaryLight: "#F5F5F5",
    accent: "#6366F1",
    accentLight: "#EEF2FF",
    success: "#059669",
    successLight: "#ECFDF5",
    warning: "#B45309",
    warningLight: "#FFFBEB",
    danger: "#E11D48",
    dangerLight: "#FFF1F2",
    text: "#111827",
    textLight: "#6B7280",
    textMuted: "#9CA3AF",
    background: "#FFFFFF",
    backgroundAlt: "#FAFAFA",
    border: "#E5E7EB",
    borderLight: "#F3F4F6",
  },
  typography: {
    fontFamily: "Plus Jakarta Sans, system-ui, sans-serif",
    headingFontFamily: "Plus Jakarta Sans, system-ui, sans-serif",
    baseFontSize: 13,
    lineHeight: 1.7,
    headingSizes: { h1: 26, h2: 18, h3: 14 },
    fontWeights: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
  },
  spacing: {
    unit: 4,
    pagePadding: "32px 40px",
    sectionGap: 5,
    componentGap: 3,
  },
  borders: { radius: 4, radiusLg: 8, width: 1 },
};

export const MINIMAL_DARK: Theme = {
  name: "Minimal Dark",
  colors: {
    primary: "#818CF8",
    primaryLight: "#1E1B4B",
    accent: "#A78BFA",
    accentLight: "#2E1065",
    success: "#34D399",
    successLight: "#064E3B",
    warning: "#FBBF24",
    warningLight: "#451A03",
    danger: "#F87171",
    dangerLight: "#450A0A",
    text: "#F1F5F9",
    textLight: "#94A3B8",
    textMuted: "#64748B",
    background: "#0F172A",
    backgroundAlt: "#1E293B",
    border: "#334155",
    borderLight: "#1E293B",
  },
  typography: {
    fontFamily: "Inter, system-ui, sans-serif",
    headingFontFamily: "Inter, system-ui, sans-serif",
    baseFontSize: 14,
    lineHeight: 1.65,
    headingSizes: { h1: 28, h2: 20, h3: 16 },
    fontWeights: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
  },
  spacing: {
    unit: 4,
    pagePadding: "28px 36px 32px",
    sectionGap: 4,
    componentGap: 3,
  },
  borders: { radius: 8, radiusLg: 12, width: 1 },
};

export const CORPORATE_GRAY: Theme = {
  name: "Corporate Gray",
  colors: {
    primary: "#1D4ED8",
    primaryLight: "#EFF6FF",
    accent: "#64748B",
    accentLight: "#F8FAFC",
    success: "#16A34A",
    successLight: "#F0FDF4",
    warning: "#D97706",
    warningLight: "#FFFBEB",
    danger: "#DC2626",
    dangerLight: "#FEF2F2",
    text: "#1E293B",
    textLight: "#64748B",
    textMuted: "#94A3B8",
    background: "#FFFFFF",
    backgroundAlt: "#F8FAFC",
    border: "#CBD5E1",
    borderLight: "#F1F5F9",
  },
  typography: {
    fontFamily: "Georgia, 'Times New Roman', serif",
    headingFontFamily: "Georgia, 'Times New Roman', serif",
    baseFontSize: 13,
    lineHeight: 1.7,
    headingSizes: { h1: 26, h2: 18, h3: 14 },
    fontWeights: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
  },
  spacing: {
    unit: 4,
    pagePadding: "32px 40px",
    sectionGap: 5,
    componentGap: 3,
  },
  borders: { radius: 4, radiusLg: 6, width: 1 },
};

export const VIBRANT_GRADIENT: Theme = {
  name: "Vibrant",
  colors: {
    primary: "#7C3AED",
    primaryLight: "#EDE9FE",
    accent: "#EC4899",
    accentLight: "#FCE7F3",
    success: "#10B981",
    successLight: "#ECFDF5",
    warning: "#F59E0B",
    warningLight: "#FFFBEB",
    danger: "#EF4444",
    dangerLight: "#FEF2F2",
    text: "#1E1B4B",
    textLight: "#6D28D9",
    textMuted: "#8B5CF6",
    background: "#FAFAFA",
    backgroundAlt: "#F5F3FF",
    border: "#DDD6FE",
    borderLight: "#EDE9FE",
  },
  typography: {
    fontFamily: "DM Sans, system-ui, sans-serif",
    headingFontFamily: "DM Sans, system-ui, sans-serif",
    baseFontSize: 14,
    lineHeight: 1.65,
    headingSizes: { h1: 30, h2: 22, h3: 17 },
    fontWeights: { normal: 400, medium: 500, semibold: 600, bold: 700, extrabold: 800 },
  },
  spacing: {
    unit: 4,
    pagePadding: "28px 36px 32px",
    sectionGap: 4,
    componentGap: 3,
  },
  borders: { radius: 10, radiusLg: 16, width: 1 },
};

export const BUILTIN_THEMES: Theme[] = [
  KOMITY_BLUE,
  MINIMAL_LIGHT,
  MINIMAL_DARK,
  CORPORATE_GRAY,
  VIBRANT_GRADIENT,
];
